###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = dolphin
$menu = rofi
$browser = firefox

$launchmenu = $menu -show drun

