background #0f1416
foreground #dee3e6
cursor #afecff
selection_background #001f27
selection_foreground #afecff

# Black
color0 #899295
color8 #40484b

# Red
color1 #ffb4ab
color9 #93000a

# Green
color2 #c0c4eb
color10 #dee0ff

# Yellow
color3 #b2cbd3
color11 #cee7ef

# Blue
color4 #85d2e8
color12 #004e5d

# Magenta
color5 #b2cbd3
color13 #344a51

# Cyan
color6 #dee0ff
color14 #c0c4eb

# White
color7 #dee3e6
color15 #bfc8cb

# Tab bar colors
active_tab_foreground   #003641
active_tab_background   #85d2e8
inactive_tab_foreground #bfc8cb
inactive_tab_background #1b2022
